sudo: required

#language: php

services:
  - docker

branches:
  only:
    - master
    - staging-ci

install:
  - docker-compose build

before_script:
  - docker-compose up -d

script:
  - docker-compose ps
  - sleep 30
  - curl -LI localhost

after_script:

notifications:
  slack: diorama-radio:JaoyLeAlhZ8e6ugkadHEdteG
