version: '2'
services:
  moodle:
    image: diorama/moodle:latest
    links:
      - moodle_db
    environment:
      MOODLE_URL: "https://example.com"
      DB_PORT_3306_TCP_ADDR: moodle_db
      DB_ENV_MYSQL_USER: moodle
      DB_ENV_MYSQL_PASSWORD: moodle
      DB_ENV_MYSQL_DATABASE: moodle
    ports:
      - "8080:80"
    volumes:
      - .log:/var/log
    restart: always

  moodle_db:
    image: centurylink/mysql:latest
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_ROOT_PASSWORD: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    ports:
      - "3307:3307"
    volumes:
      - .data/moodledb:/var/lib/mysql
    restart: always
