version: '2'
services:
  moodle:
    build:
      context: ./ver/v3.1.5
      args:
        - BOOL_REVERSEPROXY='false'
        - BOOL_SSLPROXY='false'
    image: moodle:v3.1.5
    container_name: moodle
    links:
      - moodle_db
    env_file: .env
    # environment:
    #   MOODLE_URL: "http://example.com"
    ports:
      - "80:80"
    restart: always
    # volumes:
    #   - .data/moodledata:/var/moodledata
  moodle_db:
    image: centurylink/mysql:latest
    container_name: moodle_db
    env_file: .env
    volumes:
      - .data/moodledb:/var/lib/mysql
    restart: always

# nginx-proxy networksettings
#
# networks:
#  default:
#    external:
#       name: webproxy
volumes:
  # moodledata: {}
  moodledb: {}
