version: '2'
services:
  https-portal:
    image: steveltn/https-portal:v1.1.1
    ports:
      - '80:80'
      - '443:443'
    links:
      - moodle
      - moodle_db
    restart: always
    environment:
      DOMAINS: 'moodle.example.com -> http://moodle'
      STAGE: 'production'
      # FORCE_RENEW: 'true'
  moodle:
    image: diorama/moodle:latest
    links:
      - moodle_db
    environment:
      MOODLE_URL: "https://example.com"
      DB_PORT_3306_TCP_ADDR: moodle_db
      DB_ENV_MYSQL_USER: moodle
      DB_ENV_MYSQL_PASSWORD: moodle
      DB_ENV_MYSQL_DATABASE: moodle
    ports:
      - "8080:80"
    restart: always

  moodle_db:
    image: centurylink/mysql:latest
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_ROOT_PASSWORD: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    ports:
      - "3307:3307"
    volumes:
      - .data/moodledb:/var/lib/mysql
    restart: always
